[features]
seeds = false
skip-lint = false
[programs.localnet]
testprogramyt = "zQR22LLhXfjBRB9woeHx93Tk4HDpZAwVXLNFh4VYZCb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/qiaopengjun/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
# test = "node tests/testprogramyt.js"
